[tool.poetry]
name = "escrow-revolutionized"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "escrow_revolutionized"}]

[tool.poetry.dependencies]
python = "^3.10"
py-algorand-sdk = "^1.20.2"
pyteal = "^0.20.1"
autopep8 = "^2.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
