[tool.poetry]
name = "escrow-revolutionized"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [
    {include = "scripts"}
]

[tool.poetry.dependencies]
python = "^3.10"
py-algorand-sdk = "^1.20.2"
pyteal = "^0.20.1"
autopep8 = "^2.0.1"

[tool.poetry.scripts]
deploy = "scripts.deploy.escrow.deploy_new:main"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.0"
pytest-cov = "^4.0.0"
pylint = "^2.15.9"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
